export enum CollisionFlag {
	STATIC_OBJECT = 1,
	KINEMATIC_OBJECT = 2,
	NO_CONTACT_RESPONSE = 4,
}

export enum BodyState {
	ACTIVE_TAG = 1,
	ISLAND_SLEEPING = 2,
	WANTS_DEACTIVATION = 3,
	DISABLE_DEACTIVATION = 4,
	DISABLE_SIMULATION = 5,
}
