export const FUNCTION_TEMPLATE_BY_FUNCTION_NAME: Record<string, string> = {
	addVector: 'Vector2 | Vector3 | Vector4',
	addVectorNumber: 'Vector2 | Vector3 | Vector4',
	arrayElementPrimitive: 'PrimitiveArrayElement',
	arrayElementVector: 'Vector2 | Vector3 | Vector4',
	arrayPopPrimitive: 'PrimitiveArrayElement',
	arrayPopVector: 'Vector2 | Vector3 | Vector4',
	arrayShiftPrimitive: 'PrimitiveArrayElement',
	arrayShiftVector: 'Vector2 | Vector3 | Vector4',
	debug: 'any',
	divideVectorNumber: 'Vector2 | Vector3 | Vector4',
	getObjectAttribute: 'ParamConvertibleJsType',
	getObjectAttributeAutoDefault: 'ParamConvertibleJsType',
	elementsToArrayPrimitive: 'PrimitiveArrayElement',
	elementsToArrayVector: 'VectorArrayElement',
	lengthVector: 'Vector2 | Vector3 | Vector4',
	lengthVectorArray: 'Vector2 | Vector3 | Vector4',
	mathVectorArray_1: 'MathArrayVectorElement',
	mathVectorArray_2: 'MathArrayVectorElement',
	mathVectorArray_3: 'MathArrayVectorElement',
	mathVectorArray_4: 'MathArrayVectorElement',
	mathVectorArray_5: 'MathArrayVectorElement',
	multScalarArrayVectorArray: 'Color | Vector2 | Vector3 | Vector4',
	multScalarVectorArray: 'Color | Vector2 | Vector3 | Vector4',
	multVector: 'Vector2 | Vector3 | Vector4',
	multVectorNumber: 'Vector2 | Vector3 | Vector4',
	negate: 'boolean | number',
	previousValuePrimitive: 'boolean | number | string',
	subtractVector: 'Vector2 | Vector3 | Vector4',
	subtractVectorNumber: 'Vector2 | Vector3 | Vector4',
};
