// export enum CadType {
// 	BOX = 'box',
// 	CIRCLE = 'circle',
// 	CIRCLE_2D = 'circle2D',
// 	CONE = 'cone',
// 	COPY = 'copy',
// 	CYLINDER = 'cylinder',
// 	ELLIPSE_2D = 'ellipse2D',
// 	POINT = 'point',
// 	POINT_2D = 'point2D',
// 	RECTANGLE = 'rectangle',
// 	SPHERE = 'sphere',
// 	SWITCH = 'switch',
// 	TORUS = 'torus',
// 	TRANSFORM = 'transform',
// 	TRANSFORM_2D = 'transform2D',
// }
