export enum SopType {
	ADD = 'add',
	ATTRIB_ADD_MULT = 'attribAddMult',
	ATTRIB_COPY = 'attribCopy',
	ATTRIB_CREATE = 'attribCreate',
	AXES_HELPER = 'axesHelper',
	BLEND = 'blend',
	BOX = 'box',
	BOX_LINES = 'boxLines',
	CAPSULE = 'capsule',
	CIRCLE = 'circle',
	CIRCLE_3_POINTS = 'circle3Points',
	CONE = 'cone',
	COPY = 'copy',
	CURVE_FROM_POINTS = 'curveFromPoints',
	CSS2D_OBJECT = 'CSS2DObject',
	CSS3D_OBJECT = 'CSS3DObject',
	DATA = 'data',
	DATA_URL = 'dataUrl',
	ICOSAHEDRON = 'icosahedron',
	INSTANCE = 'instance',
	MAPBOX_TRANSFORM = 'mapboxTransform',
	MATERIAL = 'material',
	NOISE = 'noise',
	PARTICLES_SYSTEM_GPU = 'particlesSystemGpu',
	PHYSICS_GROUND = 'physicsGround',
	PHYSICS_RBD_ATTRIBUTES = 'physicsRBDAttributes',
	PHYSICS_WORLD = 'physicsWorld',
	PHYSICS_PLAYER = 'physicsPlayer',
	PLANE = 'plane',
	POLAR_TRANSFORM = 'polarTransform',
	POLYWIRE = 'polywire',
	RAY = 'ray',
	RING = 'ring',
	ROUNDED_BOX = 'roundedBox',
	SHEAR = 'shear',
	SPHERE = 'sphere',
	SUBDIVIDE = 'subdivide',
	SWITCH = 'switch',
	TANGENT = 'tangent',
	TETRAHEDRON = 'tetrahedron',
	TEXT = 'text',
	TORUS = 'torus',
	TORUS_KNOT = 'torusKnot',
	TRANSFORM = 'transform',
	TUBE = 'tube',
	UV_LAYOUT = 'uvLayout',
	UV_TRANSFORM = 'uvTransform',
	UV_UNWRAP = 'uvUnwrap',
}

export enum SopTypeFile {
	FILE_DRC = 'fileDRC',
	FILE_FBX = 'fileFBX',
	FILE_GEOJSON = 'fileGEOJSON',
	FILE_GLTF = 'fileGLTF',
	FILE_JSON = 'fileJSON',
	FILE_MPD = 'fileMPD',
	FILE_OBJ = 'fileOBJ',
	FILE_PDB = 'filePDB',
	FILE_PLY = 'filePLY',
	FILE_STL = 'fileSTL',
	FILE_SVG = 'fileSVG',
}

export enum SopTypeFileMulti {
	FILE_DRC = 'fileMultiDRC',
	FILE_FBX = 'fileMultiFBX',
	FILE_GLTF = 'fileMultiGLTF',
	FILE_JSON = 'fileMultiJSON',
	FILE_MPD = 'fileMultiMPD',
	FILE_OBJ = 'fileMultiOBJ',
	FILE_PDB = 'fileMultiPDB',
	FILE_PLY = 'fileMultiPLY',
	FILE_STL = 'fileMultiSTL',
	FILE_SVG = 'fileMultiSVG',
}
