import {CATEGORY_SOP} from './Category';

import {AddSopNode} from 'src/engine/nodes/sop/Add';
import {AnimationCopySopNode} from 'src/engine/nodes/sop/AnimationCopy';
import {AnimationMixerSopNode} from 'src/engine/nodes/sop/AnimationMixer';
import {AttribAddMultSopNode} from 'src/engine/nodes/sop/AttribAddMult';
import {AttribCopySopNode} from 'src/engine/nodes/sop/AttribCopy';
import {AttribCreateSopNode} from 'src/engine/nodes/sop/AttribCreate';
import {AttribDeleteSopNode} from 'src/engine/nodes/sop/AttribDelete';
import {AttribNormalizeSopNode} from 'src/engine/nodes/sop/AttribNormalize';
import {AttribPromoteSopNode} from 'src/engine/nodes/sop/AttribPromote';
import {AttribRemapSopNode} from 'src/engine/nodes/sop/AttribRemap';
import {AttribRenameSopNode} from 'src/engine/nodes/sop/AttribRename';
import {AttribTransferSopNode} from 'src/engine/nodes/sop/AttribTransfer';
import {BboxScatterSopNode} from 'src/engine/nodes/sop/BboxScatter';
import {BlendSopNode} from 'src/engine/nodes/sop/Blend';
import {BoxSopNode} from 'src/engine/nodes/sop/Box';
import {CacheSopNode} from 'src/engine/nodes/sop/Cache';
import {CircleSopNode} from 'src/engine/nodes/sop/Circle';
import {ColorSopNode} from 'src/engine/nodes/sop/Color';
import {CopySopNode} from 'src/engine/nodes/sop/Copy';
import {DataSopNode} from 'src/engine/nodes/sop/Data';
import {DataUrlSopNode} from 'src/engine/nodes/sop/DataUrl';
import {DelaySopNode} from 'src/engine/nodes/sop/Delay';
import {DeleteSopNode} from 'src/engine/nodes/sop/Delete';
import {FileSopNode} from 'src/engine/nodes/sop/File';
import {HierarchySopNode} from 'src/engine/nodes/sop/Hierarchy';
import {LineSopNode} from 'src/engine/nodes/sop/Line';
import {MergeSopNode} from 'src/engine/nodes/sop/Merge';
import {PlaneSopNode} from 'src/engine/nodes/sop/Plane';
import {SphereSopNode} from 'src/engine/nodes/sop/Sphere';
import {SwitchSopNode} from 'src/engine/nodes/sop/Switch';
import {TextSopNode} from 'src/engine/nodes/sop/Text';
import {TransformSopNode} from 'src/engine/nodes/sop/Transform';
import {TubeSopNode} from 'src/engine/nodes/sop/Tube';

export interface GeoNodeChildrenMap {
	add: AddSopNode;
	animation_copy: AnimationCopySopNode;
	animation_mixer: AnimationMixerSopNode;
	attrib_add_mult: AttribAddMultSopNode;
	attrib_copy: AttribCopySopNode;
	attrib_create: AttribCreateSopNode;
	attrib_delete: AttribDeleteSopNode;
	attrib_normalize: AttribNormalizeSopNode;
	attrib_promote: AttribPromoteSopNode;
	attrib_remap: AttribRemapSopNode;
	attrib_rename: AttribRenameSopNode;
	attrib_transfer: AttribTransferSopNode;
	bbox_scatter: BboxScatterSopNode;
	blend: BlendSopNode;
	box: BoxSopNode;
	cache: CacheSopNode;
	circle: CircleSopNode;
	color: ColorSopNode;
	copy: CopySopNode;
	data: DataSopNode;
	data_url: DataUrlSopNode;
	delay: DelaySopNode;
	delete: DeleteSopNode;
	file: FileSopNode;
	hierarchy: HierarchySopNode;
	line: LineSopNode;
	merge: MergeSopNode;
	plane: PlaneSopNode;
	sphere: SphereSopNode;
	switch: SwitchSopNode;
	text: TextSopNode;
	transform: TransformSopNode;
	tube: TubeSopNode;
}

import {Poly} from 'src/engine/Poly';
export class SopRegister {
	static run(poly: Poly) {
		poly.register_node(AddSopNode, CATEGORY_SOP.INPUT);
		poly.register_node(AnimationCopySopNode, CATEGORY_SOP.ANIMATION);
		poly.register_node(AnimationMixerSopNode, CATEGORY_SOP.ANIMATION);
		poly.register_node(AttribAddMultSopNode, CATEGORY_SOP.ATTRIBUTE);
		poly.register_node(AttribCopySopNode, CATEGORY_SOP.ATTRIBUTE);
		poly.register_node(AttribCreateSopNode, CATEGORY_SOP.ATTRIBUTE);
		poly.register_node(AttribDeleteSopNode, CATEGORY_SOP.ATTRIBUTE);
		poly.register_node(AttribNormalizeSopNode, CATEGORY_SOP.ATTRIBUTE);
		poly.register_node(AttribPromoteSopNode, CATEGORY_SOP.ATTRIBUTE);
		poly.register_node(AttribRemapSopNode, CATEGORY_SOP.ATTRIBUTE);
		poly.register_node(AttribRenameSopNode, CATEGORY_SOP.ATTRIBUTE);
		poly.register_node(AttribTransferSopNode, CATEGORY_SOP.ATTRIBUTE);
		poly.register_node(BboxScatterSopNode, CATEGORY_SOP.MODIFIER);
		poly.register_node(BlendSopNode, CATEGORY_SOP.MODIFIER);
		poly.register_node(BoxSopNode, CATEGORY_SOP.INPUT);
		poly.register_node(CacheSopNode, CATEGORY_SOP.MISC);
		poly.register_node(CircleSopNode, CATEGORY_SOP.INPUT);
		poly.register_node(ColorSopNode, CATEGORY_SOP.MODIFIER);
		poly.register_node(CopySopNode, CATEGORY_SOP.MODIFIER);
		poly.register_node(DataSopNode, CATEGORY_SOP.INPUT);
		poly.register_node(DataUrlSopNode, CATEGORY_SOP.INPUT);
		poly.register_node(DelaySopNode, CATEGORY_SOP.MISC);
		poly.register_node(DeleteSopNode, CATEGORY_SOP.MODIFIER);
		poly.register_node(FileSopNode, CATEGORY_SOP.INPUT);
		poly.register_node(HierarchySopNode, CATEGORY_SOP.MISC);
		poly.register_node(LineSopNode, CATEGORY_SOP.INPUT);
		poly.register_node(MergeSopNode, CATEGORY_SOP.MISC);
		poly.register_node(PlaneSopNode, CATEGORY_SOP.INPUT);
		poly.register_node(SphereSopNode, CATEGORY_SOP.INPUT);
		poly.register_node(SwitchSopNode, CATEGORY_SOP.MISC);
		poly.register_node(TextSopNode, CATEGORY_SOP.INPUT);
		poly.register_node(TransformSopNode, CATEGORY_SOP.MODIFIER);
		poly.register_node(TubeSopNode, CATEGORY_SOP.INPUT);
	}
}
