export const Constants = {
	NODE_HEIGHT: 50,
	CONNECTION_VERTICAL_MARGIN: 12,
	CONNECTION_VERTICAL_SPACING: 20,
	CONNECTION_VERTICAL_START: 10,
	NODE_UNIT: 50,
	// NODE_SIZE: 50,
	// NODE_POS_MULT: 1
};
